name: CICD 

on:
  push:
    branches: [ main ]
  

jobs:
  deploy:
    name: Deploy 
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      
      - name: Deploy to development server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          script: | 
            cd /var/www/html/Laravel-demo
            git pull origin main  # Pull the correct branch (main)
            # Add any additional commands here
