name: CICD

on:
  push:
    branches: [ development ]

jobs:
  deploy:
    name: Deploy 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to development server
        uses: appleboy/ssh-action@master
        
          
          script: | 
            cd /var/www/html/Laravel-demo
            git pull origin ${{ github.ref }}
            
            
