name: Deploy Laravel Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up PHP
        run: sudo apt-get install php -y

      - name: Install Composer Dependencies
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php --install-dir=/usr/local/bin --filename=composer
          php -r "unlink('composer-setup.php');"
          composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Create .env File
        run: cp .env.example .env

      - name: Run Database Migrations
        run: php artisan migrate --force

      - name: Start Laravel Server
        run: php artisan serve --host=0.0.0.0 --port=8000
